### ISSUE TITLE
feature request: swap pipe and backslash when table mode is on 

### ISSUE THREAD

**Issue by Alok** [dhruvasagar/vim-table-mode#100]
Or add an option for that functionality. This makes typing tables much faster.

**Comment by dhruvasagar** [comment]
You can achieve this urself with the following code in your vimrc : 

```viml
augroup TableMode
  au!

  autocmd User TableModeEnabled imap \ <Bar>
  autocmd User TableModeDisabled iunmap \
augroup END
```

**Comment by Alok** [comment]
That didn't quite work, but this does:

```
augroup TableMode
  au!
  autocmd User TableModeEnabled imap <buffer> <bslash>
<Plug>(table-mode-tableize)
  autocmd User TableModeEnabled inoremap <buffer> <bar> <bslash>
  autocmd User TableModeDisabled silent! iunmap <buffer> <bslash>
  autocmd User TableModeDisabled silent! iunmap <buffer> <bar>
augroup END
```

-- Alok

**Comment by dhruvasagar** [comment]
That's odd, it worked for me though.

**Comment by dhruvasagar** [comment]
By default the `\` is the 'leader' key, so perhaps you have other leader mappings and that may conflict, or in the least cause delays. Although it's rare to have leader mappings for insert mode.
