### ISSUE TITLE
Exporting vertical lines to Latex

### ISSUE THREAD

**Issue by luis3011** [dhruvasagar/vim-table-mode#101]
http://stackoverflow.com/questions/8532762/exporting-vertical-lines-in-org-mode-table-to-latex
is there any way to do that for vim-table-mode?

**Comment by dhruvasagar** [comment]
Hi,

Vim Table Mode does not have any special export facility for latex, I would assume that option / setting would have to be applied in whatever script you use for exporting to latex.

**Comment by luis3011** [comment]
thanks, i solved
#+ATTR_LATEX: :align |c|c|
|------+-----+-----|
|    A |   B |   C |
|------+-----+-----|
| 2.34 | 2.7 | 8.9 |
| 3.67 | 4.5 | 8.9 |
|------+-----+-----|

or export to HTML

#+ATTR_HTML: :border 2 :rules all :frame border
|------+-----+-----|
|    A |   B |   C |
|------+-----+-----|
| 2.34 | 2.7 | 8.9 |
| 3.67 | 4.5 | 8.9 |
|------+-----+-----|

that works for me

**Comment by dhruvasagar** [comment]
Great, thanks for sharing.
