### ISSUE TITLE
TableModeRealign changes wrongly changes header line.

### ISSUE THREAD

**Issue by stfl** [dhruvasagar/vim-table-mode#102]
I have table in a pandoc / markdown file where I'd like to use the ReST compatible table.
I have following set in my config.

   let g:table_mode_corner_corner="+"
   let g:table_mode_header_fillchar="="

wenn I run `:TableModeRealign` the header line is converted back to `+---+---+` instead of `+===+===+`

**Comment by dhruvasagar** [comment]
Hi, did you make sure you restarted vim / sourced your vimrc after making those changes ?

**Comment by stfl** [comment]
Yes. When I do 

```echo g:table_mode_corner_corner``` 

It shows me "+" and so on..

**Comment by dhruvasagar** [comment]
Hi,

When you first add the header border line when there isn't one, it will not be treated as a 'header' border and so will end up using regular fillchar. But subsequently on invoking `:TableModeRealign` will regenerate the border correctly.

**Comment by dhruvasagar** [comment]
Let me know if you still face this issue.
