### ISSUE TITLE
having "+" as content of the cell

### ISSUE THREAD

**Issue by stfl** [dhruvasagar/vim-table-mode#103]
Hi. I trying to create a table to compare different approaches for a report. For that i want to put a couple of `++` and `--` and so on in the cells.

When putting a `++`  and running `:TableModeRealign` two `++` are also added into the border which is of course wrong and causes pandoc to not correctly draw the table...
Is it possible to prevent that or to escape the `+` ?

**Comment by Kcorab** [comment]
See https://github.com/dhruvasagar/vim-table-mode/issues/32
The ticket was closed although this issue still exist.

**Comment by dhruvasagar** [comment]
I will revisit this issue.
