### ISSUE TITLE
options for different file types

### ISSUE THREAD

**Issue by SenZhangAI** [dhruvasagar/vim-table-mode#111]
Hi, 
if I want to use corner "|" for markdown, and "+" for other file type, when I  use this:

```vim
let g:table_mode_corner = '|'
```

this global variable will influent all file types, 

if using two variables `b:table_mode_corner` and `g:table_mode_corner`, one for buffer and one for global, it may be easier to config.

There is an example of using buffer variable and global variable --- [delimitMate](https://github.com/Raimondi/delimitMate/blob/master/plugin/delimitMate.vim)

：）

**Comment by dhruvasagar** [comment]
Yes, this is an already requested feature. I have a partial implementation ready, I should be pushing this soon.

**Comment by SenZhangAI** [comment]
Thanks a lot， I found the same issue #83 , so I close this one.
This is an awesome plugin！
