### ISSUE TITLE
Custom formulas

### ISSUE THREAD

**Issue by majutsushi** [dhruvasagar/vim-table-mode#114]
At the moment table formulas can only be simple arithmetic expressions. It would be really useful if it was possible to write custom formulas that would then allow the handling of tables that contain things other than simple numbers. Thanks!

**Comment by dhruvasagar** [comment]
Well the formula engine uses eval behind the scenes so you can use viml functions exhaustively as long as you understand the input that will be given to the functions you call.

Like I have the Sum, Avg, etc, it should be fairly straight forward to build more if required.

**Comment by dhruvasagar** [comment]
Let me know if you guys need any more input regarding the same. Perhaps more documentation / examples ?

**Comment by erwin** [comment]
More documentation / examples would be fantastic.

I've been trying to get Sum working and not having much luck.

Manually Sum each column works fine...
```
|  L1 |  L2 |  L3 | L4 | Total |
|----:|----:|----:|---:|-------|
|  90 |  80 | 300 |    | 470.0 |
| 160 | 360 |     |    | 520.0 |
| 165 |     |     |    | 165.0 |
| 270 |     |     |    | 270.0 |
| 160 |  90 | 160 | 90 | 500.0 |
<!-- tmf: $5=$1+$2+$3+$4 -->
```

But I can't get it to work with the `Sum` command when using all rows...
I can only get Sum to work on a single row... `tmf: 1,5=Sum(1,1:1,4)`

```
|  L1 |  L2 |  L3 | L4 | Total |
|----:|----:|----:|---:|-------|
|  90 |  80 | 300 |    | 0.0   |
| 160 | 360 |     |    | 0.0   |
| 165 |     |     |    | 0.0   |
| 270 |     |     |    | 0.0   |
| 160 |  90 | 160 | 90 | 0.0   |
<!-- tmf: $5=Sum($1:$4) -->
```

What I would really like to do is actually eval the contents of a column, like:

```
| Measure       | Total |
|---------------|-------|
| 90+80+300     | -1    |
| 160+360       |       |
| 165           |       |
| 270           |       |
| 160+90+160+90 |       |
<!-- tmf: $2 = Sum($1) -->
```

**Comment by dhruvasagar** [comment]
I would advice you to read the following section of the README.md https://github.com/dhruvasagar/vim-table-mode#formula-expressions

The `$` references are meant to be used with specific cells, while you should be using `ranges`

**Comment by dhruvasagar** [comment]
For example, the formula for summing the entire column is `Sum(1:-1)`, which represents all rows in the current column till just before the current (target) cell

**Comment by dhruvasagar** [comment]
For your example, this is what you'd need :
```
| Measure       |       |
|---------------+-------|
| 90+80+300     | 90.0  |
| 160+360       | 160.0 |
| 165           | 165.0 |
| 270           | 270.0 |
| 160+90+160+90 | 160.0 |
 tmf: $2=eval($1) 
```

**Comment by erwin** [comment]
@dhruvasagar That was very helpful! Thank you!

I'm amazed that I had never heard about this plugin until today! So awesome!

**Comment by dhruvasagar** [comment]
@erwin no problem, I was looking at some other examples above, and I do see that I don't have support for column ranges when target is also a column.

**Comment by erwin** [comment]
Maybe this is a bug in Neovim, but I noticed when I try to run this example with `:TableEvalFormulaLine` I actually get an error:

```
Error detected while processing function tablemode#spreadsheet#formula#EvaluateFormulaLine[39]..tablemode#spreadsheet#formula#EvaluateExpr:                       
line   67:                                                                                                                                                        
E806: using Float as a String
```

Maybe it's a Neovim issue:

```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az87-780
```

```markdown
| Measure       |     |
|---------------|-----|
| 90+80+300     | 0   |
| 160+360       | 160 |
| 165           | 165 |
| 270           | 270 |
| 160+90+160+90 | 160 |
<!-- tmf: $2 = float2nr(eval($1)) -->
```

**Comment by dhruvasagar** [comment]
It appears there's a bug, i'll investigate

**Comment by mig-hub** [comment]
I was personally trying to add times like you can do in org mode with the "U" flag. Is there a way to do this?

**Comment by dhruvasagar** [comment]
@mig-hub You can parse that into a time value with something like this :

```viml
echo strptime('%d/%m/%Y %H:%M', printf('%s %s', strftime('%d/%m/%Y', localtime()), '8:45'))
```

**Comment by dhruvasagar** [comment]
@erwin I have recently pushed a change to the formula evaluation engine that fixes some issues discovered while attempting to solve for your use case. Now you should be able to see the correct calculations for the following table as an example : 

```md
| Measure       |     |
|---------------|-----|
| 90+80+300     | 470 |
| 160+360       | 520 |
| 165           | 165 |
| 270           | 270 |
| 160+90+160+90 | 500 |
<!-- tmf: $2 = float2nr(eval($1)) -->

```

**Comment by mig-hub** [comment]
Thank you @dhruvasagar , this is exactly what I was looking for. I agree that this is definitely a good route to separate functions that are very generic and can be used in other context, and then have just specific table-mode that are only used for parsing the ranges and then delegate.

This is a really nice project.
Thank you for working on this.
