### ISSUE TITLE
TableModeDisable doesn't disable the already set tables 

### ISSUE THREAD

**Issue by zelhar** [dhruvasagar/vim-table-mode#117]
Hi

So this is the behavior I have noticed which I think is a bug:

1. enable tablemode
2. create a table
3. diable table mode
4. insert more text into the row just bellow the table using the table separator "|".
5. press Esc to return to normal mode
 result: The inserted into the last row is reformatted to match the table.

Is that deliberate or a bug? If deliberate than is there a way to completely disable table mode once it has been invoked in a document without completely restarting vim or exiting/reloading the file?

**Comment by bklaase** [comment]
I noticed this happening as well. It doesn't always happen, but after manipulating a table enough times, I noticed the buffer getting modified with tablemode disabled, as soon as the cursor went over the table.

**Comment by dhruvasagar** [comment]
@bklaase This was a bug as a by-product of the auto align feature introduced recently. I have since fixed that issue. Thanks for your help.

**Comment by bklaase** [comment]
great! Thank *you* for this awesome plugin!
