### ISSUE TITLE
Is there a way to escape the table seperator?

### ISSUE THREAD

**Issue by rayman22201** [dhruvasagar/vim-table-mode#118]
I have a table that has a code example with the pipe character in the code.
e.x.
```
+------------+-------------------------------+
| table cell | here is some example code:    |
|            | ``` code |=> stuff ```        |  <----- this line breaks
+------------+-------------------------------+
```
Vim-Table-Mode treats this pipe character as a table separator, which as you can imagine,
causes strange things to happen in that table.

Is there a way to escape a pipe character so that it is not treated as a cell separator?

**Comment by dhruvasagar** [comment]
As of now there isn't a way to have this. Haven't figured out a clean / simple way to achieve this. I think using something like '`'  maybe not a bad idea.

**Comment by rayman22201** [comment]
Thank you for the quick reply :)
The back-tick **'`'** character is the standard for code samples in markdown syntax.
That would be perfect for my use case, but is it too limited?

Maybe it could be configurable like the delimiter character?

I'm not very familiar with the vim-script language, but if you showed me where to look, I could try to help by submitting a pull request. 

My first guess after looking at the code is to modify this line:
https://github.com/dhruvasagar/vim-table-mode/blob/30a3eba81628fdd099adc6dfdec8aa627c4783f7/autoload/tablemode/table.vim#L36

**Comment by dhruvasagar** [comment]
Hi,

This is rather tricky to handle with just regex.

**Comment by roneyrao** [comment]
markdown recognize backslash, e.g. `\|`. 
I generated a piece of markdown js docs by [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown), this escape style appears and works fine both in my tool and github.

**Comment by dhruvasagar** [comment]
@roneyrao That is a sensible choice. I did try a bit in the past to add support for that but the regex is becoming a bit more complex than I would have liked it to be. I'll give it another shot.

**Comment by roneyrao** [comment]
thanks for your time.

**Comment by dhruvasagar** [comment]
I have added initial support for this. So far alignment and border creation respect escaped table separators as expected, however work is required to have cell motions & formula engine to take these into account correctly. Seems like this requires a bit of refactoring to build a generalized abstraction for this and avoid duplication of code.

**Comment by dhruvasagar** [comment]
I will close this issue since I have added support for this, if there are any issues or concerns let me know. Thanks guys.

**Comment by andrewbriggs** [comment]
@rayman22201 "Is there a way to escape the table seperator?"

First grade starts with spelling separator correctly.
