### ISSUE TITLE
How to insert a column?

### ISSUE THREAD

**Issue by shaggyaxe** [dhruvasagar/vim-table-mode#119]
Hopefully this is not embarrassingly obvious.  I just can't figure out how to insert a new column.
I found nothing in the docu.  I see table-mode-delete-column.  But no table-mode-insert-column.

The way I've been doing it is to vertically copy/paste a column divider to where I need it.

Thanks!

**Comment by dhruvasagar** [comment]
Hi, as of now it's manual, there's no automated way of creating columns. I do understand a need for it, but it hasn't been built yet.
