### ISSUE TITLE
autoformat in normal mode

### ISSUE THREAD

**Issue by ashfinal** [dhruvasagar/vim-table-mode#121]
When the cursor move between lines in normal mode, some chars get auto-formatted.
Is this the expected behaviour? If so, how can I disable this?
![untitled](https://user-images.githubusercontent.com/6827900/27762757-8b086bb4-5eaa-11e7-8114-10851b4710cc.gif)

**Comment by dhruvasagar** [comment]
Hi,

This has been a recent addition to table mode. You can disable it by setting `g:table_mode_auto_align` to `0`.

**Comment by ashfinal** [comment]
Big thanks! 👍
