### ISSUE TITLE
Buffer modified when cursor on table line even though table mode disabled

### ISSUE THREAD

**Issue by myitcv** [dhruvasagar/vim-table-mode#122]
Thanks for a great plugin!

```
NVIM v0.2.1-617-g8ae16aa92
```

It seems however that the plugin is causing the buffer to be modified if the cursor is on a table line, even though I've disabled table mode.

To reproduce:

1. `:TableModeToggle` to enter table mode
2. Create a table - any table will do
3. `:TableModeToggle` to leave table mode
4. Move the cursor to a different part of the file
5. `:w` to save the file
6. Leaving the cursor away from the table for ~5 secs, verify that the buffer remains unmodified post save
7. Move the cursor back to a line in the table
8. Wait for ~5 secs and see that the buffer now becomes modified (despite us not being in table mode)

Visual demo is best: https://www.youtube.com/watch?v=c9RJGJhTdN0&feature=youtu.be

Am I doing something wrong?

**Comment by myitcv** [comment]
As a follow up, the buffer switching to a modified state can be see at ~20 secs into the video (a `+` appears beside the filename in my status line)

**Comment by dhruvasagar** [comment]
Hi, Thanks for reporting this, I had seen this before but hadn't paid enough attention to actually think it was an issue. I have now fixed this cleanly.

**Comment by myitcv** [comment]
@dhruvasagar thanks for the quick response. The new commit works for me!
