### ISSUE TITLE
An underscore char ('_') in a cell cause in wired glitches

### ISSUE THREAD

**Issue by Kcorab** [dhruvasagar/vim-table-mode#124]
An underscore char ('_') in a cell of the first or the last row breaks the formatting and the cells above and below.

edit: commit 322503e814c49416f0267f3bbeb87e1b495f0449

**Comment by dhruvasagar** [comment]
Can you share a quick screencast / asciicast ? I'll have a look

**Comment by qianlei90** [comment]
![_deepin-terminal_20180105121453](https://user-images.githubusercontent.com/5654791/34595344-291584ea-f212-11e7-9144-8869cb772768.gif)

**Comment by dhruvasagar** [comment]
Is this in the latest update ? Looks odd, will check again.

**Comment by dhruvasagar** [comment]
Nope, looks like you just have to update to the latest, it should be working as expected now.

**Comment by dhruvasagar** [comment]
Thanks for your help.
