### ISSUE TITLE
Undo / Redo

### ISSUE THREAD

**Issue by klassegeljakt** [dhruvasagar/vim-table-mode#125]
It takes many undos to undo a table update, and table updates mess up redos. Would it be possible to do an undojoin on every table update so that undos/redos are less cumbersome?

**Comment by dhruvasagar** [comment]
I believe I am doing so for the most part, can you perhaps screencast a specific scenario ? Any bulk updates I provide like removing a column, row, etc are all done to ensure they are atomic in the sense that undo / redo will respect those as single change using undojoin.

**Comment by dhruvasagar** [comment]
Hey, kindly reopen this issue if you don't think it's working as desirable.
