### ISSUE TITLE
table resize changes corsor position

### ISSUE THREAD

**Issue by torpak** [dhruvasagar/vim-table-mode#127]
whenever inputting something in a table cell, that causes it to resize, the cursor is put in a position one before the end of the current input as far as i could find out.
So entering

``|123``

in tablemode gives me:

``| 231``

What am i doing wrong?

**Comment by dhruvasagar** [comment]
Nothing I believe this is a result of an issue with trying to auto-align while in insert mode. I have fixed this by avoiding auto-align during insert mode using CursorHoldI, instead now I do it when you leave insert mode, along with being able to manually align / align on entering the table mode separator. It should work better with the latest changes.
