### ISSUE TITLE
Autoalign on Insert Mode makes typing in impossible if cell is right-aligned

### ISSUE THREAD

**Issue by jeetsukumaran** [dhruvasagar/vim-table-mode#128]
The CursorHold trigger fires on any real pause when typing, which results in all characters already typed to be flush/aligned right and the next character you type then gets inserted to the left of the word/text/number etc. 

Suggestion: only auto-align when exiting from insert mode.

**Comment by dhruvasagar** [comment]
I agree auto-align does cause a lot of issues.

**Comment by jeetsukumaran** [comment]
THANKS! As always, appreciate the work!
