### ISSUE TITLE
Command to insert a new column

### ISSUE THREAD

**Issue by wmusial** [dhruvasagar/vim-table-mode#130]
Creating a new column manually in an existing table is doable annoying. Would be nice to have "insert column left/right of cursor" commands.

**Comment by bit-garden** [comment]
While this is not a solution, you could change your corner char to |, then use [textobj-word-column](https://github.com/coderifous/textobj-word-column.vim) and you can quickly select and yank a column line, then paste it.

This does have some gotchas, like pasting just pipes at the start of the lines. This plug-in also makes it super fast to select and move columns too.

**Comment by dhruvasagar** [comment]
Thanks for the suggestion, i've been meaning to add first class support for this though. Should get around to it.
