### ISSUE TITLE
Table mode adjusts even when it is disabled.

### ISSUE THREAD

**Issue by sittim** [dhruvasagar/vim-table-mode#131]
After I disable table mode `<leader>tm`, tables still get adjusted, even if I do not want them to.

**Comment by dhruvasagar** [comment]
Are you running on the latest code ?

**Comment by sittim** [comment]
Yes, for sure.  I use plug and update it once a week.

**Comment by miostreams** [comment]
I experience the same issue. However, if I exit the file and re-open it, the module stays off.
In other words:

1. Open file for editing
2. \tm to enter table mode
3. Do some tabling stuff
4. \tm to toggle table mode off
5. Do some more playing around with data -- notice that tables keep adjusting
6. :wq to save and close the file
7. Reopen the file and do some more table editing -- no auto adjustments are made
8. \tm to toggle table mode on -- behavior repeats.

Thanks!

**Comment by sittim** [comment]
Yes, that's what I do and it works, but it does break up the workflow, so it is somewhat annoying.

**Comment by miostreams** [comment]
Ok, I just went in and completely removed all of the previous table-mode stuff (just cleaned out everything under .vim) and then grabbed it again from git, and I'm no longer seeing this behavior.
