### ISSUE TITLE
Sometimes cursor stays on the current cell when pressing |

### ISSUE THREAD

**Issue by pmalek** [dhruvasagar/vim-table-mode#132]
Sometimes when I press <kbd>|</kbd> (pipe) the cursor stays on the same cell in the table so that I have to manually change the cell either.

Gif:
![tty](https://user-images.githubusercontent.com/739996/37256543-7c3cbd46-255c-11e8-9cff-064ba1854d79.gif)

I use neovim (from master branch, version: v0.2.3-821-gd53aa0e94) and `vim-table-mode` is in default configuration

**Comment by dhruvasagar** [comment]
Likely culprit is auto-align feature, although i've tried to address this from recent commits but there still could be a small timing window within which this may happen. Are you sure you're running the latest vim-table-mode ?

**Comment by pmalek** [comment]
I just cloned it

```
commit c35fd9b104fb75017f3866a28a77cf38f61b7801 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Dhruva Sagar <dhruva.sagar@gmail.com>
Date:   Tue Feb 13 08:34:35 2018 +0530
    Remove CursorHoldI for auto-align. Fix #128
    Since auto-align in insert mode causes snags, removing it and instead
    doing it on InsertLeave instead
```

this happens most often when e.g. I use long cells (lots of text) above and then short ones (small amount of text) below (in those short ones  the cursor gets stuck).

**Comment by dbger** [comment]
It's same in vim8(ms windows)
I found it's no problem when first press 'SPACE' key then press '|'.

**Comment by dhruvasagar** [comment]
Ok, will take a deeper look.

**Comment by sjhorst** [comment]
This is a great plugin, thanks! I can replicate this bug on Vim8 custom compiled on Ubuntu 16.04.  I also just cloned today, using default configuration. The behavior and conditions are the same as pmalek describes.
