### ISSUE TITLE
Only use the alignment feature for csv files

### ISSUE THREAD

**Issue by Bersp** [dhruvasagar/vim-table-mode#143]
Hello,

First, thanks! I love your plugin, works really good for me. 
Now, I wanna know if it possible only use de alignment feature in csv files.
For example:
I wanna convert this
```csv
data, longlongdata, longdata
1.1,34,10000
1.2,22,200
1.6,10,450
```
to this, every time I update de table
```csv
data, longlongdata, longdata
1.1 , 34          , 10000
1.2 , 22          , 200
1.6 , 10          , 450
```
or something similar, easy to read but still using de CSV format.

Sorry for my english,
Thanks in advance!

**Comment by dhruvasagar** [comment]
I would suggest to use another plugin better designed for this feature. github.com/godlygeek/tabular is what i've used a lot and it does the job well.
