### ISSUE TITLE
Conflict with vimwiki

### ISSUE THREAD

**Issue by ElModdy** [dhruvasagar/vim-table-mode#144]
The plugin works fine but when the extension is for example .md, vimwiki overwrites the settings.
![screen](https://user-images.githubusercontent.com/18534491/54623678-4c632480-4a6c-11e9-9fb0-0ba991635fec.png)
My .vimrc looks like this:
```
let g:table_mode_corner_corner='+'
let g:table_mode_header_fillchar='='

let g:vimwiki_table_mappings=0
let g:vimwiki_table_auto_fmt=0

```
I really appreciate any kind of help.

**Comment by dhruvasagar** [comment]
There's a ftplugin/markdown.vim that adds some settings for table mode to make it work as per gfm spec. If you need to override any of those, you'll need to do so in a after/ftplugin. Kindly refer to #142.

**Comment by ElModdy** [comment]
Thanks for the reply.
Sorry for my ignorance but I don't have any "ftplugin".

**Comment by ElModdy** [comment]
Solved
