### ISSUE TITLE
Option to not align table cell text

### ISSUE THREAD

**Issue by aloneinkyoto** [dhruvasagar/vim-table-mode#145]
I'm working with pandoc markdown grid tables.

When vim-table-mode aligns the table text for e.g. centered or right aligned columns, it inserts spaces to visually align the text in the editor.

When processed by pandoc, this can result in the table text being rendered as a code listing - this is because text preceded  by 4 spaces is interpreted as a code block by pandoc.

Would it be possible for vim-table-mode to have an option to align the column separators but not the text itself (i.e. leave the text left aligned within the cell)?

I've attached a picture to demonstrate the problem.

![tables_rendering](https://user-images.githubusercontent.com/1399251/54705997-d75c2180-4b35-11e9-8e96-e0cec708f4c6.png)

**Comment by korakinos** [comment]
It is possible to `let g:table_mode_auto_align = 0`, but this disables *all* auto-alignment, not just within cells. Or as a workaround, place your alignment colons only as the last step after you finished editing your table and disabled table-mode.

Agreed that this would be good to have!

**Comment by dhruvasagar** [comment]
I pushed a new configuration `g:table_mode_ignore_align`, this is disabled (set to 0) by default, however, if it is enabled table mode will ignore the alignment characters on the header and always left align. This can also be set on a buffer to override global.

**Comment by korakinos** [comment]
Amazing, thanks!
