### ISSUE TITLE
'||' header border expansion not working

### ISSUE THREAD

**Issue by elig0n** [dhruvasagar/vim-table-mode#147]
`||` does not expand but `|-|` does.

`g:table_mode_separator` is `|`
`g:table_mode_corner` is `+`
`g:table_mode_corner_corner` is `|`

**Comment by dhruvasagar** [comment]
Which filetype ? I am not able to reproduce this.
If there's no previous row, it should create `|-+-|`, also do double check the settings for the filetype / buffer to make sure it's not being overriden from a ftplugin or autocmd.

**Comment by elig0n** [comment]
As I can't reproduce it now either (and plugin was upgraded a few times as well)  I'm closing it
