### ISSUE TITLE
.md filetype overrrides .vimrc settings

### ISSUE THREAD

**Issue by zelhar** [dhruvasagar/vim-table-mode#148]
I have set the following configuration in my .vimrc. in order to conform with pandoc markdown table format:

```
let g:table_mode_corner = '+'
let g:table_mode_corner_corner='+'
let g:table_mode_header_fillchar='='
```

Now it works fine unless I edit an .md file type (which therefore defeats the purpose of my above settings). When I open such a file type, the variables are redefined to '|' (corner) and '-' (header fillchar).  The global settings remains as in the .vimrc. it looks like somewhere the .md is predefined and cannot be overridden by the global variable. Is that by design?

**Comment by zelhar** [comment]
So, it seems like there is a simple override which is to put the buffer variables in '.vim/after/ftplugin/markdown.vim' :

```
let b:table_mode_corner = '+'
let b:table_mode_corner_corner='+'
let b:table_mode_header_fillchar='=' 
```


Sorry for spamming.

**Comment by dhruvasagar** [comment]
Yes, this has been raised as an issue a number of times by now. I will add this to the documentation to make sure people are aware. Thanks.
