### ISSUE TITLE
Reference a different table

### ISSUE THREAD

**Issue by jgallen23** [dhruvasagar/vim-table-mode#15]
I have a file that has a few tables in it and it would be great if I could reference a value from another table in my formula or pull in the value into a cell from the other table so I don't have to have two references to it.  Is there any way to do this?

**Comment by dhruvasagar** [comment]
Hi, I am not convinced if this feature is needed. I will close this for now (been open far too long). We can look at it again in future if it becomes relevant. Thanks for your suggestions.
