### ISSUE TITLE
TableSort only sorts first column

### ISSUE THREAD

**Issue by oblitzitate** [dhruvasagar/vim-table-mode#156]
The issue is `:TableSort[!]` only sorts first column regardless of where the cursor is. Whereas `<Leader>ts` seems to work fine for any column.

I'd also like to suggest a key binding for sorting in _descending_ order.

**Comment by dhruvasagar** [comment]
@oblitzitate Thanks for reporting this, I was testing the code and from the looks of it this seems to be a bug with vim itself. For some reason the cursor position is altered (`col('.') returns 1`) when calling via a command as opposed to the mapping. I will try to get back to this and test more if there's a way to avoid this.
