### ISSUE TITLE
Better support for whitespace delimiter

### ISSUE THREAD

**Issue by varac** [dhruvasagar/vim-table-mode#159]
I'd like to create a table out of this:

```
Test:       1       2   3 4
Line2:   5 6     7    8
```

When I use `:Tableize/ `, the table looks like this:

```
| Test:  |  |  |   |   |  |  | 1 |  |   |  |  |  |   | 2 |  |  | 3 | 4 |
| Line2: |  |  | 5 | 6 |  |  |   |  | 7 |  |  |  | 8 |
```

which makes sense from a technical point of view.

The desired table would be:

```
| Test:  | 1 | 2 | 3 | 4 |
| Line2: | 5 | 6 | 7 | 8 |
```
So there should be an option to consider subsequent delimeters without anyting in betweeen as one, or a special treatment for whitespace delimiters in this case. What do you think ?

**Comment by dhruvasagar** [comment]
You can use this `:Tableize/\s\+` to get the same result as you expect above. The portion you specify for the command `:Tableize` is a regular expression (vim regex) and you can use a modified version that makes sense for your use case.
