### ISSUE TITLE
Sorting only works for first character when sorting a column of ints

### ISSUE THREAD

**Issue by lancekrogers** [dhruvasagar/vim-table-mode#160]
Table ordering a column of ints sorts by first digit only

column with values 1-12 sorts like this: [1,10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9]

**Comment by dhruvasagar** [comment]
@lancekrogers TableSort leverages `:sort` by column, `:TableSort n` should work better in this context but you can also work with more complex patterns, I would recommend read `:h :sort`.
