### ISSUE TITLE
Add (realign) to tutorial

### ISSUE THREAD

**Issue by axil** [dhruvasagar/vim-table-mode#161]
Table created. Header changed. Table needs to be realigned. Otherwise it is not a valid rst anymore.

`\tr` realigns it.

This is basic functionality. I had to search for it in the sources. I'd suggest adding it to the plugin description right after table creation. It is way more important for ordinary users than formulas or sorting.

**Comment by dhruvasagar** [comment]
@axil Sure, i'll add it in the README, however, it is mentioned in `:h table-mode`, that's generally a much more detailed place to look for documentation.

**Comment by axil** [comment]
I knew it should be somewhere! Thanks )
