### ISSUE TITLE
Can't delete column

### ISSUE THREAD

**Issue by BSDxxxx** [dhruvasagar/vim-table-mode#164]
:TableModeDeleteColumn

:mess

E492: 不是编辑器的命令: TableModeDeleteColumn

**Comment by dhruvasagar** [comment]
@BSDxxxx Can you share some sample table text on which you attempted to do this ? Also let me know which column you attempted to delete.

**Comment by BSDxxxx** [comment]
@dhruvasagar 

```
| name | age | height |
|------|-----|--------|
| Tom  | 11  | 12     |
| Mike | 12  | 13     |
```

can't delete any column, same error message above.
Also can't see 'TableModeDeleteColumn' command in command list
I'm using vim8.1 in cygwin.

**Comment by dhruvasagar** [comment]
@BSDxxxx There is no command `:TableModeDeleteColumn`, there is a mapping provided which is mappinged to <kbd>\<Leader>tdc</kbd> by default for deleting a column
