### ISSUE TITLE
[Request] Horizontal Tables

### ISSUE THREAD

**Issue by Corey-Keller** [dhruvasagar/vim-table-mode#167]
What I have:
```
	+-----------+-----------+
	| Heading 1 | Heading 2 |
	+===========+===========+
	| H1I1      | H2I1      |
	+-----------+-----------+
	| H1I2      | H2I2      |
	+-----------+-----------+
	| H1I3      | H2I3      |
	+-----------+-----------+
	| H1I4      | H2I4      |
	+-----------+-----------+
```

What I want:
```
	+===========+------+------+------+------+
	| Heading 1 | H1I1 | H1I2 | H1I3 | H1I4 |
	+===========+------+------+------+------+
	| Heading 2 | H2I1 | H2I2 | H2I3 | H2I4 |
	+===========+------+------+------+------+
```

This works as-is, (sort of, at the end I have to manually delete the === row and replace it with a regular one), but there's no way of visually distinguishing the header column.

EDIT: I've updated it with a potential way of distinguishing the header column.

**Comment by dhruvasagar** [comment]
@Corey-Keller I am not quite sure how useful this is. I have never seen this table format used for something practical that I know of. Can you share some background on the use case ?

**Comment by Corey-Keller** [comment]
It's in a vim help file. Really the 'use case' was just that I didn't like all the wasted vertical space (the vertical table took up maybe 1/3 of the 80 character width, but fit perfectly horizontally.

**Comment by dhruvasagar** [comment]
@Corey-Keller I will have to decline this request at the moment.
