### ISSUE TITLE
Incorrect horizontal line separators when editing markdown with Neovim

### ISSUE THREAD

**Issue by ttrei** [dhruvasagar/vim-table-mode#168]
From README.md:
> In the second line (without leaving Insert mode), enter | twice. The plugin will write a properly formatted horizontal line
```
| name | address | phone |
|------+---------+-------|
```

When editing a markdown file (extension .md or .markdown) using Neovim 0.4.3 (Debian testing), the horizontal line looks **different**:
````
| name | address | phone |
|------|---------|-------|
````

I get the expected behavior when editing a non-markdown file (e.g., test.txt).
I also get the expected behavior when using Vim 8.1, irrespective of the file extension.

I minimized my configuration to avoid interactions with other plugins:
~/.vimrc is empty
~/.vim contains only latest vim-table-mode (commit 0af25d72):
```
$ tree ~/.vim -L 5
/home/ttrei/.vim
└── pack
    └── other
        └── start
            └── vim-table-mode
                ├── autoload
                ├── CHANGELOG.md
                ├── doc
                ├── ftplugin
                ├── Gemfile
                ├── Gemfile.lock
                ├── plugin
                ├── Rakefile
                ├── README.md
                ├── t
                ├── URL
                ├── VimFlavor.lock
                └── youtube.png
```
```
$ cat ~/.config/nvim/init.vim
set runtimepath+=~/.vim,~/.vim/after
set packpath+=~/.vim
source ~/.vimrc
```

**Comment by dhruvasagar** [comment]
@ttrei Hi, thanks for reporting the issue, I will refer you to this - https://github.com/dhruvasagar/vim-table-mode/issues/148, from what I understand the defaults provided for markdown are as per spec, however, as you'll find in that issue, you can override those if required.

**Comment by ttrei** [comment]
Thanks!

Btw this was not true, I made a mistake:
> I also get the expected behavior when using Vim 8.1, irrespective of the file extension.
Looks like Neovim and Vim behavior is the same here.

**Comment by dhruvasagar** [comment]
@ttrei I expected that to be the case, thanks for confirming.
