### ISSUE TITLE
Releases State

### ISSUE THREAD

**Issue by ejiek** [dhruvasagar/vim-table-mode#170]
There were no releases from April 2017 but project is maintained and updated.
Have you decided to give up on them?

I'm wondering because there is an [Archlinux package in AUR](https://aur.archlinux.org/packages/vim-table-mode/) which is based on you releases.
If you are not planning on updating them any more, we should take action on Archlinux side of things to have up-to-date of this package.

**Comment by dhruvasagar** [comment]
That's a valid expectation, over the years vim plugin management has moved to a pure git based approach and hence I felt there's little value in pushing releases. However, I wasn't aware of packages being maintained for this. Thanks for bring this to my attention, I will be more than happy to bring back release version like I did before.

**Comment by dhruvasagar** [comment]
I just pushed a new release. I will ensure I push new releases with semantic versioning as I did before. Hope that helps. Thanks for letting me know @ejiek .
