### ISSUE TITLE
g:table_mode_corner overridden by ftplugin/markdown_tablemode.vim

### ISSUE THREAD

**Issue by Luxoboy** [dhruvasagar/vim-table-mode#172]
Hello,

When I set `let g:table_mode_corner='+'` in my `.vimrc`, a `let b:table_mode_corner = '|'` is executed in the `ftplugin/markdown_tablemode.vim` which overrides the global setting – when opening a `.md` file.

I debugged that by launching Vim with the `-V20` option.

Thanks!

**Comment by dhruvasagar** [comment]
@Luxoboy This is a known issue, in order to override it you must place your overrides in an after plugin in a directly such as `after/ftplugin/table-mode-overrides.vim`

**Comment by dhruvasagar** [comment]
I will try to add this to the documentation since there have been several issues opened for this exact issue.
