### ISSUE TITLE
Table updates influences change and jump lists

### ISSUE THREAD

**Issue by rwblokzijl** [dhruvasagar/vim-table-mode#173]
Hello all,

When a table is re-adjusted the actions that are used to do so seem to be added to the jump and change lists. This break undo/redo functionality in vim as well as repeat command.

Information about how these fundamental internal vim buffers can be kept clean can be found here:
https://unix.stackexchange.com/questions/327759/how-to-suspend-vim-history

Other than this i love table mode, it is the plugin i use the most. Keep up the good work.

**Comment by dhruvasagar** [comment]
Hi Thanks for reporting this, I consider this a high priority issue, i'll go looking.

**Comment by bew** [comment]
Hello, did you make progress on that front? Just started to use this plugin and undo is acting weirdly with auto updates

**Comment by dhruvasagar** [comment]
Will post update in

**Comment by dhruvasagar** [comment]
@bew I have pushed a fix, kindly test it out and let me know.

**Comment by rwblokzijl** [comment]
Amazing! What a wonderful christmas present!

**Comment by rwblokzijl** [comment]
Undos work now, which is great. But the repeat button `.` doesn't work yet. I don't know if its related to this.

**Comment by dhruvasagar** [comment]
@rwblokzijl I am going to take that up separately.
