### ISSUE TITLE
g:table_mode_corner unresponsive in neovim

### ISSUE THREAD

**Issue by sjhorst** [dhruvasagar/vim-table-mode#177]
I'm having a strange issue where setting g:table_mode_corner='+' does not seem to be working. The corner characters between cells remains a pipe character '|' which breaks pandoc's grid_tables extension. Setting g:table_mode_corner_corner='+' works fine. I'm running neovim 0.4.3.

**Comment by dhruvasagar** [comment]
Which filetype are you doing this in ? Markdown ?

**Comment by sjhorst** [comment]
Yes, working in markdown and applying the settings in my ftplugin directory.

**Comment by Karamaz0V1** [comment]
I'm having the same issue (nvim v0.4.3).

`g:table_mode_corner` works for other filetypes (like `.txt`) but not for markdown.

**Comment by dhruvasagar** [comment]
@sjhorst @Karamaz0V1 Kindly refer to https://github.com/dhruvasagar/vim-table-mode/issues/172, let me know if that solves your problem.
