### ISSUE TITLE
Formula line format

### ISSUE THREAD

**Issue by eyJhb** [dhruvasagar/vim-table-mode#179]
Previously I could have formula lines like so:

```
| Date       | Mes  | Used |
|------------|------|------|
| 2018-07-12 | 7372 | 4    |
> tmf: $1,3=4
```

But suddenly, they need to be some ugly HTML comment thing?

```
| Date       | Mes  | Used |
|------------|------|------|
| 2018-07-12 | 7372 | 4    |
<!-- tmf: $1,3=4 -->
```

I am using a `.md` file, and it is detected as markdown files by vim. Any suggestions?

**Comment by dhruvasagar** [comment]
@eyJhb Double check what the `filetype` of the current file is. Also check what `set commentstring` gives you. The `commentstring` setting's value is used to keep the formula line commented out.
Needless to say, it's also possible to override these settings in an ftplugin yourself, however typically the defaults should work well.

**Comment by eyJhb** [comment]
The filetype is markdown 

```
:set filetype?
>  filetype=markdown
```
But I see that commentstring gives me the HTML syntax, and that might be it.
So I guess I just need to tweak that, thanks! :)
