### ISSUE TITLE
Help mentions wrong movement keys

### ISSUE THREAD

**Issue by bodograumann** [dhruvasagar/vim-table-mode#183]
The help states:

> Move between cells :
> 	Now you can move between cells using table mode motions
> 	'<Leader>t[hjkl]' to move left | down | up | right cells respectively.
> 	You can use |table-mode-map-prefix| option to define the prefix
> 	mapping to be used before 'hjkl'. The left | right motions wrap around
> 	the table and move to the next | previous row after the last | first
> 	cell in the current row if one exists.

It seems to me though, that those keys are not mapped and instead you have to use `[|`, `]|`, `{|` and `}|`.
Those are actually more convenient, I think, but the help is confusing.

**Comment by dhruvasagar** [comment]
@bodograumann Not sure where you're getting that, but the current documentation reflects exactly what you describe.

**Comment by bodograumann** [comment]
I updated, double checked and it is also wrong here in the repository: https://github.com/dhruvasagar/vim-table-mode/blob/master/doc/table-mode.txt#L54-L60

**Comment by dhruvasagar** [comment]
@bodograumann My bad, I was looking in the wrong place here - https://github.com/dhruvasagar/vim-table-mode/blob/master/doc/table-mode.txt#L395-L398
