### ISSUE TITLE
Unbind Keymappings

### ISSUE THREAD

**Issue by typkrft** [dhruvasagar/vim-table-mode#189]
let g:table_mode_disable_mappings = 0 or 1
let g:table_mode_disable_tableize_mappings = 0 or 1

Don't seem to disable key mappings. Maybe I am not understanding what is supposed to happen here, or doing something incorrectly. Is there a way to unbind all key mappings?

**Comment by dhruvasagar** [comment]
The only remaining mapping after setting those two should be the insert mode mapping for `|`, I am not sure if disabling that is a good idea.
Can you elaborate on what you're really trying to do ?

**Comment by typkrft** [comment]
I am trying to remove normal mode keybindings such as `<leader>t` because I've remapped them with which key already. Because the original ones are still there it makes an extra entry in my which key setup. You can see this labeled as `t -> +prefix` in the screenshots found [here](https://imgur.com/a/MRZe9IZl).

**Comment by dhruvasagar** [comment]
@typkrft There are other configurations meant to change / override those few default ones.

**Comment by typkrft** [comment]
No problem, I can remap them individually. I thought there might be a way to automatically disable the default ones with a single setting. Thanks for this great plugin.

**Comment by UTFeight** [comment]
why isn't there an option for this tho?

I think making the defaults optional (if it wasn't a breaking change) would make more sense

**Comment by dhruvasagar** [comment]
@UTFeight These are plug mappings, if you provide your own, it overrides the defaults. If you want to disable all mappings, then you might as well not install the plugin...
