### ISSUE TITLE
it is possible to undo ?

### ISSUE THREAD

**Issue by LuisBL** [dhruvasagar/vim-table-mode#192]
The `u` undo does not work when we are in TableMode

**Comment by mnaei** [comment]
I have created a simple command for myself that turns a table back into a delimiter. Essentially, you highlight a table and the command remove all lines that have |--+--| format and replaces all remaining separators "|" with the delimiter ","

An official de-table command would be a nice addition

**Comment by dhruvasagar** [comment]
@mnaei there is an existing issue with undo, essentially a lot of updates to the table aren't being clubbed together as single changes so that they can be undo'd properly. I should get to it soon.

**Comment by bew** [comment]
Related #173
