### ISSUE TITLE
vim table mode supprort group heading

### ISSUE THREAD

**Issue by thevan96** [dhruvasagar/vim-table-mode#196]
How group the heading table?

![Screenshot 2021-02-28 at 19 37 52](https://user-images.githubusercontent.com/47932916/109418718-7402eb80-79fc-11eb-8527-5b9415e3104f.png)
![Screenshot 2021-02-28 at 19 38 20](https://user-images.githubusercontent.com/47932916/109418748-854bf800-79fc-11eb-90ad-0607c7c4681c.png)

**Comment by dhruvasagar** [comment]
As of now there's no support for merging of cells / defining cells that span multiple columns. This is also applicable to headers. For the time being I am in favor of adding this to keep things relatively simple.
