### ISSUE TITLE
Formula don't work in file end with .md

### ISSUE THREAD

**Issue by shipleyxie** [dhruvasagar/vim-table-mode#201]
| file——name | new | old |
|------------|-----|-----|
| 1       | 1   | 0   |
| 2      | 1   | 1   |
| 3   | 1   | 0   |
| 4  | 1   | 0   |
| 5  | 1   | 0   |
| 6  | 0   | 1   |
| Total      |     |     |

Formula don's work in a temp.md file.
Could you give me some suggestion?

**Comment by dhruvasagar** [comment]
@shipleyxie Thanks for reporting this issue, I have pushed a fix, it should be working fine now.
