### ISSUE TITLE
g:table_mode_corner does not appear to work at all

### ISSUE THREAD

**Issue by SirYancy** [dhruvasagar/vim-table-mode#205]
No matter what character I set for this option, it always uses the pipe '|'. It always used to work, but now does not seem to work no matter what I do. I've tested it on multiple machines and operating systems.

**Comment by dhruvasagar** [comment]
@SirYancy It seems to be working, also the passing tests indicate the same. Is this for Markdown files ?

**Comment by SirYancy** [comment]
It's a markdown file. It seems that it does work if I change the file
extension to rst. It's alright. I think I have a workflow that will work.
Sorry to bother.

**Comment by dhruvasagar** [comment]
@SirYancy It's been raised a bunch of times, but the right way to override the settings for markdown files is by doing it in an `after/ftplugin`. This has come up several times and if you search in the issues you'll find a bunch of references to it.
I will make it a point to add more info in the readme for this.
