### ISSUE TITLE
Org mode compatible formulas

### ISSUE THREAD

**Issue by farao** [dhruvasagar/vim-table-mode#209]
Since the standard vim-table-mode tables have the same syntax like the emacs org mode tables, it would be a very cool thing to be able to reuse the org mode style formulas as well. https://orgmode.org/org.html#Advanced-features => The org mode formulas begin with `+TBLFM`, so if vim-table-mode shall keep the current syntax it would be easy to simply allow a second formula language next to the existing one in case the line starts with `#+TBLFM` instead of `# tfm`.

If that's not wanted or not possible, it would be nice to have a solution for the problem that both vim-table-mode and emacs org mode only consider the formula if there's no line above (between table and formula) that is not a valid vim-table-mode/emacs org mode formula - thus currently it's not possible to simply duplicate the formula in both styles and have both beneith the table.

**Comment by dhruvasagar** [comment]
@farao Emacs formulas are fairly complex, I am going to decline adding this. Perhaps this can be introduced in the future if there's more demand for it.

Feel free to contribute towards this, if you can.
