### ISSUE TITLE
table_mode_corner is not picked up

### ISSUE THREAD

**Issue by ruedigerblock** [dhruvasagar/vim-table-mode#210]
Moin !

I'd like to setup grid-tables in Markdown files.

```
+---+---+
|Foo|Bar|
+===+===+
+ 1 | 2 |
+---+---+
```

To do so I configured:
```
let g:table_mode_corner = '+'
let g:table_mode_corner_corner='+'
let g:table_mode_header_fillchar='='
```
in my ~/.vimrc.
This works as expected in any file which does not end with *.md.

In Markdown Files I get:
```
+---|---+
|Foo|Bar|
+===|===+
+ 1 | 2 |
+---|---+
```
To achieve want I desire, I have to uncomment:
```
let b:table_mode_corner = '|'
```
in '~/.vim/bundle/vim-table-mode/ftplugin/markdown_tablemode.vim'

Thus I suspect that this setting supersedes my setting in ~/.vimrc.

I don't know if this is a bug or expected. But it took quite some time to come up with this workaround.

**Comment by dhruvasagar** [comment]
@ruedigerblock For markdown & rst documents, these overrides need to be placed in an after plugi n`/after/ftplugin/markdown.vim`

**Comment by naught101** [comment]
@dhruvasagar that doesn't seem to work for me. I put those lines above in `~/.vim/after/ftplugin/markdown.vim`, and I  still get:

```
let table_mode_corner
table_mode_corner      +
let b:table_mode_corner
b:table_mode_corner      |
```

**Comment by naught101** [comment]
Ok adding this to the file helped:

```
let g:table_mode_corner='+'
let g:table_mode_corner_corner='+'
let b:table_mode_corner='+'
let b:table_mode_corner_corner='+'
```
