### ISSUE TITLE
Rebind keys to move between cells

### ISSUE THREAD

**Issue by tim-hilt** [dhruvasagar/vim-table-mode#211]
`[|`, `]|`, `{|` and `}|` are pretty awkward to type, at least for me. Can those keys be rebound to tab, shift-tab and enter to go to the next cell, previous cell and downwards? I'm used to those keybindings, because Obsidian uses them. Here's a gif that shows, how those bindings work there.
![Peek 2022-02-17 08-26](https://user-images.githubusercontent.com/16037579/154426644-061d820f-d978-47d2-92e4-f03053f82a79.gif)

**Comment by tim-hilt** [comment]
I noticed, that the gif cuts off screenkey! Let me know if I should record it again.

**Comment by dhruvasagar** [comment]
You can change these mapping by changing the following configurations :

```
call s:SetGlobalOptDefault('table_mode_motion_up_map', '{<Bar>')
call s:SetGlobalOptDefault('table_mode_motion_down_map', '}<Bar>')
call s:SetGlobalOptDefault('table_mode_motion_left_map', '[<Bar>')
call s:SetGlobalOptDefault('table_mode_motion_right_map', ']<Bar>')
```
