### ISSUE TITLE
How to center content

### ISSUE THREAD

**Issue by baojiliu** [dhruvasagar/vim-table-mode#218]
I'm looking at the docs, and I see that there is something about alignment (:let g:table_mode_align_char=':')
But, I'm not quite sure how to use it. Any tips?

Expected:
```
| Name | Size |
|:----:|:----:|
| A    | 100  |
```
Get:
```
| Name | Size |
|------|------|
| A    | 100  |
```

My ```init.vim```
```
Plug 'dhruvasagar/vim-table-mode'
let g:table_mode_corner='|'
let g:table_mode_align_char=":"
```

**Comment by dhruvasagar** [comment]
@baojiliu What filetype are you working with ?

**Comment by baojiliu** [comment]
```md```

**Comment by dhruvasagar** [comment]
@baojiliu Markdown files override the vimrc configs on `Filetype` event and have `g:table_mode_corder='+'`, which is likely throwing the alignment off. If you want to use those configs, you'll need to set them from an autocmd to override for markdown files. Or use the correct border (you can remove the border and add a new one to see and then add the alignment markers again)
