### ISSUE TITLE
Visual mode issue

### ISSUE THREAD

**Issue by xbladesub** [dhruvasagar/vim-table-mode#219]
How can I disable this in block visual mode? I tried to use 'I' and 'a' in block visual mode, but it seems like this plugin functionality overlaps default vim bindings
![Screen Shot 2022-08-04 at 11 04 33 AM](https://user-images.githubusercontent.com/45129790/182754363-b2c8c940-87ed-45bf-8bb1-87e727a292a5.png)

**Comment by dhruvasagar** [comment]
@xbladesub It'll help if you read the docs. The text objects provided by the plugin are `i|` and `a|` following vim design of representing inside and around a table cell.

These are active only inside a table, when table mode is enabled so ideally these do not come in your way. However, if you really want to disable these you could do the following :

```viml
let g:table_mode_cell_text_object_i_map = '<Nop>'
let g:table_mode_cell_text_object_a_map = '<Nop>'
```
