### ISSUE TITLE
Is there a command or a way to unalign tables, i.e revert table back to previous configuration?

### ISSUE THREAD

**Issue by kalyan860** [dhruvasagar/vim-table-mode#220]
Let's say I convert a comma seperated values or tab seperated values to table; The table mode puts in pipe symbols instead of those delimiters. I know I can just undo those changes. But if I open the file again after a long time, I need the table to be in its original comma seperated style to be able to copy it to excel or any other program like mail.

**Comment by dhruvasagar** [comment]
Table Mode does provide this.
You have 2 options :
1. If you enable persistent undo, you'll be able to undo back to the original content even after vim restarts
2. You can do something like `:%s/|/,/g` followed by `:%s/^,//g` and `:%s/,$//g`
