### ISSUE TITLE
new line with `||` does not work any more

### ISSUE THREAD

**Issue by LuisBL** [dhruvasagar/vim-table-mode#221]
```
| name | address | phone |
                                          ^
```
if we type ENTER
```
in Insert mode

| name | address | phone |
                          ^
```

```
| name | address | phone |
                          ^
```

if we type ENTER we get:

```
+------+---------+-------+
|      |         |     ^ |
| name | address | phone |
+------+---------+-------+
```

No way to add || in an new line because no way to go to the new line

**Comment by dhruvasagar** [comment]
@LuisBL I am not sure what you mean, if you type `| |` on the next row it will add a new empty cell. If you add `||` (without a space) it will add a border line.

**Comment by LuisBL** [comment]
Sorry my bad I was expecting || put my cursor on a new line. My bad.

thank you so much for this wonderfull code !
