### ISSUE TITLE
Formula operations on rows

### ISSUE THREAD

**Issue by engeljh** [dhruvasagar/vim-table-mode#225]
Is there a simple way of , e.g., summing the members of each column and printing the answers to each sum in the bottom row?  That is, can you do in one formula for rows (e.g. adding them columnwise) what it's easy to do for columns (adding then row-wise)?  Right now, it seems you have to write a separate formula for each column that you want to sum the members of.  If it's not currently possible to do the operations all at once, might it be possible to add that ability?

**Comment by dhruvasagar** [comment]
You would need to implement your own custom function I believe @engeljh

**Comment by dhruvasagar** [comment]
Perhaps https://github.com/dhruvasagar/vim-table-mode/issues/214 would be helpful in that regard
