### ISSUE TITLE
How to install with lazy.nvim

### ISSUE THREAD

**Issue by Hello-LuisWu** [dhruvasagar/vim-table-mode#226]
How to install with lazy.nvim

**Comment by dhruvasagar** [comment]
@Hello-LuisWu You should be able to install it like any other vim plugin, kindly refer to lazy.nvim docs. 

```viml
require("lazy").setup({
  "dhruvasagar/vim-table-mode",
})
```

This should work, however, I haven't tested it. Everything in vim-table-mode is autoloaded so only gets loaded when you use it.

**Comment by Hello-LuisWu** [comment]
> @Hello-LuisWu You should be able to install it like any other vim plugin, kindly refer to lazy.nvim docs.
> 
> ```viml
> require("lazy").setup({
>   "dhruvasagar/vim-table-mode",
> })
> ```
> 
> This should work, however, I haven't tested it. Everything in vim-table-mode is autoloaded so only gets loaded when you use it.
If possible, I'd love for you to redevelop it with lua to improve its performance in nvim @dhruvasagar
