### ISSUE TITLE
autoenable on certain filetype

### ISSUE THREAD

**Issue by astephanh** [dhruvasagar/vim-table-mode#228]
Hello,

how can i automatically enable table mode on certain file types like markdown?

i tried this in after/ftplugin/markdown.lua but then i always got two messages and need to press return to get rid of it

ftplugin/markdown.lua
```
vim.api.nvim_call_function("tablemode#Enable", {})
```

**Comment by dhruvasagar** [comment]
@astephanh Kindly check your setup, it feels like you're calling this mulitiple times, perhaps from separate ftplugins ? I tested with both `ftplugin/markdown/custom.vim` and `after/ftplugin/markdown/markdown.lua` and I don't see the behavior you describe. I only see 1 message and it works as expected.
