### ISSUE TITLE
Is There a Way to Disable the "Table Mode Enabled" Notification?

### ISSUE THREAD

**Issue by WantenMN** [dhruvasagar/vim-table-mode#235]
Whenever I enable table mode in vim, it consistently displays a notification informing me that table mode has been enabled. While this notification might be helpful for new users, it interrupts my workflow as a regular user. I would like to disable this notification so that I can work without unnecessary interruptions.

![Screenshot_2024-02-25-00-32-56_409](https://github.com/dhruvasagar/vim-table-mode/assets/41904684/75b831aa-a2d1-4494-962b-447632f8ffa4)

**Comment by dhruvasagar** [comment]
@WantenMN Yes, you can check `:h table-mode-verbose`, basically set `g:table_mode_verbose=0` to disable these notifications.
