### ISSUE TITLE
Bug: Duplicated tag `table-mode-disable-mappings` in vimdoc file

### ISSUE THREAD

**Issue by polirritmico** [dhruvasagar/vim-table-mode#236]
**Description**

Hi, after  e7695fad5c9db6920f1d0a090bf9d1195a5d4146 I got a `Duplicate tag` error after `helptags` execution over `table-mode.txt`. This is done automatically by installing the plugin through lazy.nvim.

Output error:

```
Failed (1)
    ○ vim-table-mode  markdown      ■ docs failed
        ...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:84: Vim:E154:
        Duplicate tag "table-mode-disable-mappings" in file /home/myuser/.local/
        share/nvim/lazy/vim-table-mode/doc//table-mode.txt
```

In case it is useful, this is the function that lazy.nvim uses under the hood:

```lua
-- lazy.nvim/lua/lazy/manage/task/plugin.lua ln 77
  run = function(self)
    local docs = self.plugin.dir .. "/doc/"
    if Util.file_exists(docs) then
      self.output = vim.api.nvim_cmd({ cmd = "helptags", args = { docs } }, { output = true }) -- This fails
    end
  end,
```

Lazy plugin configuration:

```lua
  {
    "dhruvasagar/vim-table-mode",
    ft = "markdown",
    init = function()
      -- Avoid polluting <leader>t mappings. (keep <leader>tm for enable)
      vim.g.table_mode_disable_tableize_mappings = 1

      -- FIX: Really slow performance: https://github.com/dhruvasagar/vim-table-mode/issues/227
      vim.g.table_mode_syntax = 0

      vim.g.table_mode_corner = "|"
    end,
  },

```

---

**System info:**

> NVIM v0.9.5
> Build type: Release
> lazy.nvim: v10.17.0
> LuaJIT 2.1.0-beta3
> Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc  -Wall -Wextra -pedantic -Wno-unused-> parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/include -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5_build/cmake.config -I/var/tmp/portage/app-editors/neovim-0.9.5/work/neovim-0.9.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

Edit: Added the lazy plugin config

**Comment by dhruvasagar** [comment]
I am aware of this, will push out a fix soon.
