### ISSUE TITLE
Execute formulas without vim

### ISSUE THREAD

**Issue by MartyLake** [dhruvasagar/vim-table-mode#239]
Hello,

Amazing plugin, I use it with vimwiki to create md tables with formulas, and it works great for me.

However, I have to share some of those markdown files with other colleagues that may use different editors.
Do you know if the formula can be executed without vim? 

Best,

**Comment by dhruvasagar** [comment]
@MartyLake Since this is built using vimscript, as of now there isn't a way to execute it outside of vim. I feel like that would be outside the scope of this plugin.

**Comment by MartyLake** [comment]
Thanks for your answer @dhruvasagar .

What is the name of that function or methodology, so that I can research alternative ways to execute the formula, even in the absence of vimscript ? I found https://github.com/tgrosinger/md-advanced-tables/blob/main/docs/formulas.md but the formulas are slightly different. Or maybe the concept of having table formulas in markdown is not so established yet ?

**Comment by dhruvasagar** [comment]
@MartyLake This is a custom implementation that I built from scratch. It basically has a parser that parses the expression and then identifies, translates and evaluates expressions to get the result
