### ISSUE TITLE
Support for pandoc (markdown) tables

### ISSUE THREAD

**Issue by magthe** [dhruvasagar/vim-table-mode#31]
[pandoc](http://johnmacfarlane.net/pandoc/README.html)'s brand of markdown supports an impressive range of table syntaxes.  Some of them are nicely supported by `table-mode`, but not all.  In particular I can't work out any way of writing [multiline tables](http://johnmacfarlane.net/pandoc/README.html#multiline-tables) or [grid tables](http://johnmacfarlane.net/pandoc/README.html#grid-tables) (which also supports multilines).

I would love to see `table-mode` extended to support this a bit better.

**Comment by berce** [comment]
Excellent work!

A further improvement could be to allow a multiline header. Now, if there are fillchars requested at the 3rd line of the table, header_fillchar will be used. So if the header uses multiple lines, it doesn't work. It would be nicer if the header_fillchar is used on the second line that requests fillchars.

I 'd like to get this:

~~~
+------+------+
| Item | Mass |
|      | (kg) |
+======+======+
| 1    | 3.0  |
+------+------+
| 2    | 3.5  |
+------+------+
~~~

When typing:

~~~
||
| Item | Mass |
| | (kg) |
||
| 1 | 3.0 |
||
| 2 | 3.5 |
||
~~~

But now I get

~~~
+------+------+
| Item | Mass |
|      | (kg) |
+------+------+
| 1    | 3.0  |
+------+------+
| 2    | 3.5  |
+------+------+
~~~

**Comment by dhruvasagar** [comment]
Multiline cells is a bit hard at the moment and I am not sure I want to support it, I think it would add a lot of complexity and make things difficult for the formula engine. I don't make any assumptions with respect to the borders as an indication for row separators, they're only there for aesthetic and convenience and not a necessity.

I would suggest to just go with :
```
|------+-----------|
| Item | Mass (Kg) |
|======+===========|
| 1    | 3.0       |
| 2    | 3.5       |
|------+-----------|
```

**Comment by thriveth** [comment]
@dhruvasagar Sorry to re+open this item, but your suggested solution does only work for tables in which e.g. the units are quite simple. If it were "erg s^{-1} cm^{-1} \AA^{-1}", it doesn't work. This is not the case for your typical web developer, of course, but as a physicist, it would be very convenient to be able to do multiline headers because the journals want them. But I realize it might be very complex to implement.

**Comment by dhruvasagar** [comment]
Ok I will revisit this in that case. My initial thought process is that I will introduce a new configuration option that declares you are going to use bordered cells, which means that a cell would be identified by borders and not just the line numbers, it may be tricky to implement but i'll try to abstract it in a way as to not impact the existing flows. This should allow for both multiline headers and cells within the table. Let me know your thoughts.
