### ISSUE TITLE
When the tablecorner-char is in a Cell, then the fillchar ...

### ISSUE THREAD

**Issue by Kcorab** [dhruvasagar/vim-table-mode#32]
above or below also will be a tablecorner-char.

|--------+-------------|
| number | orientation |
|-------:+------------:|
|     -1 |           - |
|      0 |           + |
|      1 |           + |

Now type '|' '|' and you get:

|--------+-------------|
| number | orientation |
|-------:+------------:|
|     -1 |           - |
|      0 |           + |
|      1 |           + |
|--------+-----------+-|

**Comment by dhruvasagar** [comment]
I am not able to reproduce this anymore, I guess it got fixed along the way during some of my refactoring attempts. Kindly reopen this issue if you feel it still persists for you.

**Comment by Kcorab** [comment]
Hello Mr. Sagar,
I reopen the issue #32 because it is still exist.

If I have got the tablecorner-char (in this case '+') in a cell,
like the following, then the tablefill-char above or below also will be the tablecorner-char.
I try to show you this issue on the following impractical example.
```
|-------+----------------------|
| Name  | His/her favorit char |
|-------+----------------------|
| Maria | '#'                  |
| Aaron | '+'                  |
| Isaac | '~'                  |
|-------+----------------------|
```
In this example are no problems.
But now Aaron and Isaac want to switch her favorite chars.
Aaron have got the '~' and Isaac have got the '+'.

What happend?
```
|-------+----------------------|
| Name  | His/her favorit Char |
|-------+----------------------|
| Maria | '#'                  |
| Aaron | '~'                  |
| Isaac | '+'                  |
|-------+--+-------------------|
           ^
```
The tablefill-char under Isaacs new favorite-char '+' is also a '+', but it should be a '-'.
The same artifact you will see, if Maria have got the '+' as her favorit char. The tablefill-char direct above will be a '+' instead of a '-'.

I know, my english knowledge are very poor. I hope you understand me.

**Comment by dhruvasagar** [comment]
Yea I understand, will take another look to see if I can work around this issue.
