### ISSUE TITLE
Inserting a new column with I adds header border row

### ISSUE THREAD

**Issue by idbrii** [dhruvasagar/vim-table-mode#45]
If I use :TableModeEnable and create a simple table:

```
| a | b |
```

Then, from normal mode I type `I|` to begin inserting a new first column (I want to add a new cell to the table before 'a'), my text is transformed into a header row:

```
|---+---|
```

I would expect:

```
|| a | b |
```

So if I kept typing `z` I would get:

```
| z | a | b |
```

I have similar problems when using `I|` with a block selection to insert a new column on several lines too. (First line is header row and the right thing happens for other rows.)

I would guess this is because table-mode is seeing two adjacent Bar characters and interpreting that as a header. Is it possible to require that the last inserted character is the right Bar? (From the help, I assumed `||` would act like an imap, but it is not an imap.)

Maybe you could check the current and previous characters under the cursor?

```
getline('.')[col('.')-2:col('.')-1] == '\|\|'
```

(Not sure how that would fit in your double bar detection code.)

It could be cool if table mode detected this pattern and did the right thing for all header border rows (fills them in with header filler instead of taking them as a single cell), but I'm not sure how you'd handle subsequent input (which would be inserted inside the header row).

**Comment by dhruvasagar** [comment]
Hey I haven't been able to dig around to fix this issue, but i'd like to add that all you need to do is add a 'space' or some 'text' before you add the initial `|` and that works like expected (as a work around for now)

**Comment by dhruvasagar** [comment]
I think adding the space as a work around should suffice. I don't see this as a major pain point so closing this for now.
