### ISSUE TITLE
TableModeEnable vimwiki error

### ISSUE THREAD

**Issue by fugokidi** [dhruvasagar/vim-table-mode#47]
When I enter :TableModeEnable in vimwiki file, some error occurs:

Error detected while processing function tablemode#Enable..<SNR>41_SetActive..<SNR>41_ToggleSyntax..ta
blemode#SyntaxEnable:
line    1:
E867: (NFA) Unknown operator '\%%'
E475: Invalid argument: Table /^\s*\(\%\%\)\?\s*\zs|.\+|\ze\s*$/ contains=TableBorder,TableSeparator,T
ableColumnAlign containedin=ALL

There is table support in vimwiki, but I wanted to use table-mode so that I can use formula.

**Comment by dhruvasagar** [comment]
hmm well I guess `%%` is the vim-wiki commentstring. I'll try to address this issue.

**Comment by ntnn** [comment]
Is there anything new on this? I just stumbled upon that problem as well.

**Comment by dhruvasagar** [comment]
Hey sorry, I couldn't get around to fixing this, i'll check it out again and try to push a fix in couple of days.

**Comment by dhruvasagar** [comment]
Unfortunately, it looks like vimwiki provides it's own mappings & commands for working with / creating tables. Looks like it isn't compatible with vim-table-mode and there are a bunch of conflicts. I am going to close this for now and come back if there is sufficient demand for this.

**Comment by dhruvasagar** [comment]
Kindly refer to #110 for info regarding fix made to allow vim table mode to work with vimwiki.
