### ISSUE TITLE
Mapping to Add Horizontal Borders?

### ISSUE THREAD

**Issue by jeetsukumaran** [dhruvasagar/vim-table-mode#52]
Is there a way to easily add horizontal borders to a table?

e.g., given:

    h1,h2,h3,
    a,a,a,
    b,b,b

the tabelize operation (``\tt``) results in:

    | h1 | h2 | h3 |
    | a  | a  | a  |
    | b  | b  | b  |

Now I would like to add horizontal borders to the header row. It would be nice if some option, e.g. ``\th``
would draw an appropriate line at the current cursor position if the cursor is positioned within a table. Maybe ``\th`` would draw a line below and ``\tH`` draw a line above? So that, e.g,, if the cursor were at cell with ``h1``, hitting ``\th`` and then ``\tH`` and then moving down to the row of "b's" and hitting ``\th`` would result in:

    +----+----+----+
    | h1 | h2 | h3 |
    +----+----+----+
    | a  | a  | a  |
    | b  | b  | b  |
    +----+----+----+

As there are many styles for the horizontal border,  it might be a desirable option would be a triplet ``\th#``, where # is a style number. This would allow for plain borders (e.g., style "0") at the top and bottom of the table, and a more advanced border (e.g., style "1", with alignment markers) separating the header row from the border. 

Alternatively, if this is too clumsy, a global variable to control horizontal rule styles. 

In either case, just the ability to render even a simple border (with column joins markers) would be useful.

**Comment by dhruvasagar** [comment]
Is it too combersome to go and add them yourself using `||`?

**Comment by jeetsukumaran** [comment]
Ah, OK. I saw that key-mapping in the help, but did not realize that this was what it does. It does indeed fulfill the basics of this request. And some simple mappings such as:

    nmap <Leader>th o<bar><bar><ESC>
    nmap <Leader>tH O<bar><bar><ESC>

make things pretty seamless.

Thanks for a great plugin!

**Comment by dhruvasagar** [comment]
No problem, thanks for your feedback :)

PS: that mapping requires the table mode to be active.

**Comment by jeetsukumaran** [comment]
You're welcome. And yes, will probably have to find a hook to trigger the mapping and unmapping when entering/leaving table mode.

**Comment by dhruvasagar** [comment]
Table Mode offers autocmds `TableModeEnabled` and `TableModeDisabled` to hook into for such a use case.

**Comment by jeetsukumaran** [comment]
Excellent! Well-designed like the rest of the plugin!
