### ISSUE TITLE
[Feature Request] editing the table afterwards break the table

### ISSUE THREAD

**Issue by shibumi** [dhruvasagar/vim-table-mode#54]
When I change the content of the table afterwards it will break the table. Is there any chance to fix this?

**Comment by dhruvasagar** [comment]
Hi, can you explain the use case in a bit more detail ? What exactly broke and how ?

**Comment by shibumi** [comment]
When I have a table.. and change content in the table after I build the table the table will break.

First Table before I added some X 
Second table after I added some X

Is there a way to fix automatically the table when I change content of a cell after building the table ?

![lastimg](https://cloud.githubusercontent.com/assets/3833685/5856850/0522ea96-a247-11e4-8bc8-ea1e7d4f20aa.png)

**Comment by dhruvasagar** [comment]
Vim table mode provides a mapping <kbd><Leader>tr</kbd> for re-align the table when needed, also you could just re-add a <kbd>|</kbd>  again after removing one anywhere in the table and that would also realign the table.

**Comment by shibumi** [comment]
thx
