### ISSUE TITLE
cannot invoke help from within vim

### ISSUE THREAD

**Issue by gamStar** [dhruvasagar/vim-table-mode#58]
I just installed (or tried to at least) table-mode and got past the first few errors, but typing 

:h table-mode

yields only the 'E149: Sorry, no help for table-mode' error message.

I have tried all the installation options but the first two did not work. I then did the brute force copy of the three files into the right places, but that only worked when I copied the entire tablemode subdirectory (not just the tablemode.vim file). 

I strongly suspect that I have messed up the installation somehow, is there an updated one documented somewhere?

:: paul

PS. Updated because of automatic spelling mistakes!

**Comment by dhruvasagar** [comment]
Hi,

For the help to work in VIM, you need to run a command ':helptags ~/.vim/doc', if you were using a plugin manager like pathogen / vundle / neobundle they do this for you so you don't have to.

You can read more about it in `:h :helptags`

**Comment by dhruvasagar** [comment]
Btw I will strongly suggest to use a plugin manager, it will make things easier for you.

**Comment by gamStar** [comment]
Thanx for the quick reply!  That worked.

I actually tried to use pathogen.  The installation of pathogen itself went ok but the 'git submodule add . . .’ command returned the error

fatal: Not a git repository (or any of the parent directories): .git

and I didn’t want to spend the rest of the afternoon sorting that one out . . .

Thanx again.

:: paul

**Comment by dhruvasagar** [comment]
Well that's the case when you have your `.vim` directory under version control using git, which is a common practice however not a necessity. Instead of doing `git submodule add ...` you can instead use `git clone ...` inside your `vim/bundle` directory, that would achieve the same result.

**Comment by gamStar** [comment]
Thanx again - I’ll give that a try

:: paul

**Comment by dhruvasagar** [comment]
np, i'll close this ticket for now, you can raise another one if you face an issue.
