### ISSUE TITLE
Header and body separated by alternate `table-mode-fillchar`

### ISSUE THREAD

**Issue by jeetsukumaran** [dhruvasagar/vim-table-mode#60]
Pandoc's [grid-table](http://johnmacfarlane.net/pandoc/README.html#tables) format has an line separating the header from the body consisting of `=`.

~~~
: Sample grid table.

+---------------+---------------+--------------------+
| Fruit         | Price         | Advantages         |
+===============+===============+====================+
| Bananas       | $1.34         | - built-in wrapper |
|               |               | - bright color     |
+---------------+---------------+--------------------+
| Oranges       | $2.10         | - cures scurvy     |
|               |               | - tasty            |
+---------------+---------------+--------------------+
~~~

When editing the table, the realignment is confused by the `=` bar, and does not recognize that the header row and the body row are part of the same table: i.e., each side is re-aligned independently.  Is there a way to communicate that this is, in fact, one unified table? Just changing the `table-mode-fillchar`, to `=`, of course, does not work.

**Comment by dhruvasagar** [comment]
Hey, looks like there is a gap in the docs :/, I added a new option recently, you need to set `g:table_mode_header_fillchar` to set the char for the header if you want it different from the regular fillchar.

**Comment by jeetsukumaran** [comment]
This works perfectly! Thank you!

**Comment by dhruvasagar** [comment]
np!
