### ISSUE TITLE
Ignore `<Bar>`s inside cell (suggestion)

### ISSUE THREAD

**Issue by axil** [dhruvasagar/vim-table-mode#64]
Is there a way to have a cell containing a `<Bar>` symbol that will be ignored by your plugin?

**Comment by dhruvasagar** [comment]
Not as of now. Can you give me some examples for more clarity on the use case ?

**Comment by axil** [comment]
That's the rest source:
https://raw.githubusercontent.com/axil/blog/master/content/software/django_to_jinja.rst

and that's the rendered result:
http://axil.github.io/django-templates-to-jinja2-vocabulary.html

I've managed to workaround the issue by replacing all '|' symbols to '/' symbols, formatting, turning off the plugin and then replacing them back. But maybe there's a better way.

**Comment by axil** [comment]
The downside of this workaround is that I have to manually change '|' to '/' every time I want to update the table layout (and by search-and-replace afterwards, which is not a problem).

**Comment by dhruvasagar** [comment]
As of now I can't think of a better way really.

One option would be to write it down in csv and then using `Tableize` to transform it rather than relying on 'on the fly' auto formatting.

**Comment by dhruvasagar** [comment]
I'll try to think of some way I could support for this, at the moment it sounds hard unless you're willing to consider changing the border seperator.

**Comment by axil** [comment]
> One option would be to write it down in csv and then using Tableize to transform it rather than relying on 'on the fly' auto formatting.

It has the same drawback as my workaround: updating the layout after an edit will break the table structure.

> consider changing the border seperator.

I ain't really sure if ReST supports other separators. 

Here's their guidelines on taming `Bar`s inside cells:

http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#grid-tables

**Comment by axil** [comment]
Do you know how they addressed the issue in the emacs plugin?

**Comment by dhruvasagar** [comment]
No, I don't. They seem to have a `\vert` for something like this, not sure how they might be handling the case. I'd recommend researching how does rst provide support for pipe character inside of the cell.

**Comment by axil** [comment]
I see.

I have already. The link I've given above describes how:

http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#grid-tables

**Comment by dhruvasagar** [comment]
Yea I saw that, not very helpful unfortunately.

**Comment by axil** [comment]
Indeed so. While their recipes are ok for manual formatting, they are no good for the on-the-fly mode.

I've found that my implementation of rst accepts backslashed Bars:

https://raw.githubusercontent.com/axil/blog/master/content/software/django_to_jinja.rst

So the next version of my workaround is: `'<,'>s:\\|:,,:`, edit table, then back again `'<,'>s:,,:\\|:`

**Comment by kminh** [comment]
@axil does RST support escaping the pipe in a table? i.e. http://docutils.sourceforge.net/docs/user/rst/quickref.html#escaping

If it does, how about ignoring `\|` when realigning @dhruvasagar ? I bet no one needs `\` at the end of a cell. At least we can have an option, maybe.

**Comment by dhruvasagar** [comment]
That would be a lot easier and saner I believe :)

**Comment by mzlogin** [comment]
As of now, this issue still exists, any evolve? @dhruvasagar

**Comment by dhruvasagar** [comment]
Sadly not yet. I am starting to add features again. This will basically require tweaking of my regex patterns. Will look into it this weekend.

**Comment by mzlogin** [comment]
Glad to hear that, full of expectation.

**Comment by jcromero** [comment]
Why is this issue open if you now can escape the `|` char as `\|` to be ignored as column separator?

**Comment by axil** [comment]
@jcromero I confirm, this is no longer an issue now, safe to be closed. Thanks, @dhruvasagar!
