### ISSUE TITLE
Support for '=' lines (suggestion)

### ISSUE THREAD

**Issue by axil** [dhruvasagar/vim-table-mode#67]
The rst specs (http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#grid-tables) imply that table header (\<th>) should be separated from the table body (\<td>) using the '===' separator:

    +---------+---------+
    | header1 | header2 |
    +=========+=========|
    | data1   | data2   |
    +---------+---------+

The substitution of = to - is trivial, but subsequent editing breaks table layout.

Is it possible to make table-mode plugin treat '=' the same way as '-'?

**Comment by axil** [comment]
oops, it seems to be implemented already, although apparently has not made it into the docs yet .

**Comment by axil** [comment]
I've updated readme in my pull request to include this feature.

**Comment by dhruvasagar** [comment]
Yea, thanks!
