### ISSUE TITLE
Allow empty line before formula line for markdown

### ISSUE THREAD

**Issue by m42e** [dhruvasagar/vim-table-mode#68]
For Markdown there must be an empty line after a table to be detected correclty. With a formula line directly after the table this is not fulfilled. Is it possible to allow a blank line and have the line still useable?

**Comment by dhruvasagar** [comment]
interesting, I did not know of this. i'll have a look I suppose

**Comment by camfowler** [comment]
Ran into this issue today. Rendering the table using iA Writer and it doesn't render the table unless there is an empty line after it. My workflow currently involves inserting the newline when needing to render out for preview, then removing it when I need to run TableEvalFormulaLine.

**Comment by dhruvasagar** [comment]
@camfowler Thanks for sharing, I shall expedite this.
