### ISSUE TITLE
Format issue when cell string contains `|`

### ISSUE THREAD

**Issue by mzlogin** [dhruvasagar/vim-table-mode#72]
I have a table like this

```
| calc | result |
|------|--------|
| a&b  | 0      |
| a^b  | 3      |
| a|b  | 3      |
```

but when I use `<leader>tr` to reformat it, it becomes

```
| calc | result |
|------|--------|
| a&b  | 0      |
| a^b  | 3      |
| a    | b      | 3 |
```

neither `a|b` nor `a\|b` can work well, and 

```
`a|b`
```

cannot work well too, is there any writing method I can format my table normally?

**Comment by dhruvasagar** [comment]
Not as of now, this is being discussed here - https://github.com/dhruvasagar/vim-table-mode/issues/64. I will be implementing something very soon.
