### ISSUE TITLE
Invoke realignment after editing table without typing |

### ISSUE THREAD

**Issue by thirtythreeforty** [dhruvasagar/vim-table-mode#73]
Hello!  This is an awesome plugin.

I have a slight ergonomics improvement to suggest.  Currently, when I have a table such as the following:

```
|---------------|----------------|--------------------------|
| this is       | a sample table | with fairly long columns |
| value         | value          | value                    |
| another value |       %        | another value            |
|---------------|----------------|--------------------------|
```

And my cursor is positioned in the (empty) cell marked with a `%`, I can invoke `ci|` ("change in cell"), and type new text:

```
|---------------|----------------|--------------------------|
| this is       | a sample table | with fairly long columns |
| value         | value          | value                    |
| another value | new text             | another value            |
|---------------|----------------|--------------------------|
```

The table is now unaligned.  Of course this is easy to fix with a quick `:TableModeRealign`.  Would it be possible to invoke this automatically when exiting insert mode and the cursor is positioned anywhere in a table?

**Comment by dhruvasagar** [comment]
That is actually a very neat suggestion.

**Comment by githorse** [comment]
Why not update *during* the edit, in real time? For huge tables this might be slow, but I'm guessing it'd be unnoticeable in most cases. Could be an optional setting, perhaps.

**Comment by dhruvasagar** [comment]
The best that can be achieved and works accurately is using 'CursorHold,CursorHoldI', the reason for that is realign itself manipulates the text and as a result can have weird behavior when simply adding a new column value without 

This implies that the table will be realigned with a small delay, which I believe is acceptable given that accuracy is more important.

**Comment by dhruvasagar** [comment]
Kindly play around with the new changes and let me know what you guys think. Based on that I will see if it's worth trying to do it as we type or to keep it as how i've implemented it for now.

**Comment by githorse** [comment]
Awesome! Works as advertised. Only snag on the real-time updating is that the `updatetime` used by `CursorHold` is set by default at 4000 (ms), which is way too long in this context. Setting it to around 500 works great. However, I'm not really sure I really want to change `updatetime` globally without understanding the implications. 

Maybe you can define a `g:table_mode_update_time` that overwrites the `updatetime` while in TableMode and restores it on leaving TableMode? (I realize that may be getting a bit complicated.)

**Comment by dhruvasagar** [comment]
That sounds better. Will do.

**Comment by dhruvasagar** [comment]
Ok looks like this works reasonably well. I shall close this ticket then. Thanks for your feedback and suggestions.
