### ISSUE TITLE
Sorting with negative numbers

### ISSUE THREAD

**Issue by hein09** [dhruvasagar/vim-table-mode#76]
Hi,
great plugin, thanks for your awesome work!
Unfortunately, i can't get the sorting to work correctly.
My dataset is e.g.:

config    | value 
----------|-----------
 AA       |     -0.637495 
 AB       |     -1.368379 
 BC       |     -0.365109 
 BD       |     -0.334333 
 CC       |      0.362374 
 DE       |      0.050831 

If i now try to sort this for column 2 i get 

config    | value 
----------|----------
DE       |      0.050831
CC       |      0.362374
BD       |     -0.334333
BC       |     -0.365109
AA       |     -0.637495
AB       |     -1.368379

explicitely sorting via `:TableSort n` just pulls the AB-value on top, regardless if the data has been sorted before or not. 
Thanks for your help!

**Comment by dhruvasagar** [comment]
Hey thanks for filing a bug, technically this is a bug in vim itself since I am just using the native vim `:sort` which seems to be failing to sort negative numbers. I'll see what I can be done.

**Comment by hein09** [comment]
I see. thanks anyways, i'll try and find a patch for vim itself, then!

**Comment by OliKn** [comment]
On Linux you could use `sort` from the GNU coreutils.
`!sort -n` I get:

    -1.368379
    -0.637495
    -0.365109
    -0.334333
    0.050831
    0.362374

**Comment by dhruvasagar** [comment]
Yes I am aware of it, I did have a look at that, was part of "I'll see what I can do". I'll try to use that if it's available. I could potentially roll out my own sorting too, it may even turn out to be easier, though it might not perform as well.

**Comment by hein09** [comment]
I found a working patch for the internal sorting on the vim mailing list (https://groups.google.com/forum/#!topic/vim_dev/GkDT1K5qxuQ).
Maybe it can still be merged into upstream, it had been deemed ok then.

**Comment by dhruvasagar** [comment]
That was posted in 2010. I really doubt if it will get merged in. It will be easier for me to roll out my own in viml :)

**Comment by wladston** [comment]
Amazing how a good path has been hanging for 6 years. That's the main reason why people are moving en masse to Neovim.
