### ISSUE TITLE
Enhancement: Cell formatting

### ISSUE THREAD

**Issue by addisonamiri** [dhruvasagar/vim-table-mode#79]
I was hoping there could be support added for cell formatting. The goal would be to allow for things like dollar signs or a specific number of decimal places in the cells. I ran into the need when using formulas. I was trying to have a table of money but even after I removed the dollar signs it was summing them with a single decimal place. Not the biggest deal but it would be a nice thing to have.

**Comment by dhruvasagar** [comment]
Hi, it should work with multiple decimal places. eg.)

| Test  | Header     |
|-------+------------|
| val1  | 10.1234    |
| val2  | 23.421     |
| val3  | 46123.123  |
| total | 46156.6674 |
/* tmf: $4,2=Sum(1:-1) */

The above table computation does respect multiple decimal places.

Perhaps you were doing something different, kindly provide more info.

**Comment by addisonamiri** [comment]
I was thinking of this case:

| Test | Header |
|:-------+-------:|
| val1 | 1.00 |
| val2 | 2.00 |
| val3 | 3.00 |
| total | 6.0 |
/* tmf: $4,2=Sum(1:-1) */

Instead of this it would be nice to be able to specify to use two decimal
places instead of one. Maybe it could detect if trailing zeroes are present
and follow them that way. I was originally thinking of a way to specify
something like:

/* tmf: format(2, dollar) */

or something like that. I was thinking of the way you're able to specify
cell format in Excel. If you can think of a better solution (which I'm
almost certain one exists) I'd be interested. The only other thing I could
think of would be something with a regex. On first glance though, it seems
like it would be difficult to take pre-existing text and modify it to fit a
regex.

**Comment by dhruvasagar** [comment]
Hi, sry I haven't come back to this in a while. You can use inbuild vim functions to achieve this. You can replace your formula with something like this : 

`/* tmf: $4,2=printf('%.2f', Sum(1:-1)) */`

I don't believe this is something should be handled / supported by the plugin directly. While I do have good support for formulas, formatting of numbers etc shouldn't have to be something handled by me. It's better left to the author to use what is appropriate.

I'll close this issue for now, you may reopen / discuss further if required. Thanks for your suggestion.

**Comment by dhruvasagar** [comment]
Here is a better formula for entire column : 

`/* tmf: $4,2=Sum(1:-1); $2=printf('%.2f', $2) */`
