### ISSUE TITLE
Can't use vim-table-mode on *.tex files.

### ISSUE THREAD

**Issue by Kcorab** [dhruvasagar/vim-table-mode#81]
If I try to use vim-table-mode on a *.tex file I get the following error message:

Fehler beim Ausführen von "function tablemode#Enable[1]..<SNR>56_SetActive[2]..<SNR>56_ToggleSyntax[2]..tablemode#SyntaxEnable":
Zeile    1:
E867: (NFA) Unknown operator '\%)'
E71: Ungültiges Zeichen nach \%
E475: Ungültiges Argument: Table /^\s_(\%)\?\s_\zs|.+|\ze\s*$/ contains=TableBorder,TableSeparator,TableColumnAlign containedin=ALL

**Comment by dhruvasagar** [comment]
Kindly share your vim-table-mode settings

**Comment by Kcorab** [comment]
vim-table-mode settings? Where can I find them? In my vimrc I haven't defined such settings, so I think I use the default settings.

**Comment by dhruvasagar** [comment]
Ok, can you provide your vim version details ?

**Comment by Kcorab** [comment]
See [pastebin](http://pastebin.com/raw/3Zr9gDbj) please.

**Comment by dhruvasagar** [comment]
Thanks, i'll try and make more sense of it

**Comment by t-b** [comment]
On my vim the aligmaps `\tt` shortcut clashed with the vim-table-mode one.

I've worked around the issue for me with defining:

```vim
" Use AlignMaps \tt mapping, instead of vim-table-mode's one
autocmd FileType tex map \tt <Plug>AM_tt
```

in my vimrc.
