### ISSUE TITLE
Entering table_mode_separator does not behave correctly

### ISSUE THREAD

**Issue by gamStar** [dhruvasagar/vim-table-mode#84]
After the ex command :TableModeEnable with the table_mode_separator set to the usual '|', when I type the '|' in input mode the text '<Plug>(table-mode-tableize)' appears instead.

It has been several months since I last used TableMode, which I find very useful, so I have no idea what I might have changed to create this incompatibility. My ignorance extends to the following as well:

- I do not know how to check what version I am using
- I do not know how to uninstall reliably (so that I can install the latest version)

Any help with this would be greatly appreciated. Thanx!

**Comment by dhruvasagar** [comment]
Hi,

In order to check the version you could just look at the README.md inside table-mode plugin.
Can you share your vim-table-mode configuration and vim version info?

**Comment by gamStar** [comment]
The vim version is 7.4 (compiled Mar 12 2015 18:31:16)

I think that the table-mode version is 4.6.3, but the README is not in my .vim directory anywhere that I could see. I looked instead in the Downloads directory (I am on a Mac) and the README in the vim-table-mode-master says 4.6.3

There is no file called vim-table-mode, only table-mode.vim, is that what you need to see?

[table-mode.txt](https://github.com/dhruvasagar/vim-table-mode/files/192605/table-mode.txt)

Note that I had to change the extension to .txt for the drag and drop to work.

**Comment by dhruvasagar** [comment]
No I meant any configuration you may have put in your vimrc for vim-table-mode. Also perhaps you can share your vimrc, looks like maybe some setting could be interfering.

**Comment by gamStar** [comment]
Here is my .vimrc. Note that I have commented out some lines at the end of the file that I thought might be interfering, but it made no difference.

[vimrc.txt](https://github.com/dhruvasagar/vim-table-mode/files/193645/vimrc.txt)

Again note that I changed the name of the file from .vimrc to vimrc.txt so that dragging and dropping would work.

**Comment by dhruvasagar** [comment]
Hi,

Are you doing this in some specific filetype ? Kindly let me know.

**Comment by gamStar** [comment]
Hi,

Thanx for getting back to me.

I am writing a markdown file that will be input into Pandoc. The filetype is ‘markdown’.

Are there any tests that you can think of that I can do here to get more information?

Thanx!

:: paul

**Comment by dhruvasagar** [comment]
Not as of now, I am just trying to see if I can reproduce the issue.

**Comment by dhruvasagar** [comment]
I see you're using Vundle, but I don't see vim-table-mode being managed with the help of Vundle. Kindly switch to that, because right now I am unsure of how you've installed vim-table-mode. You may delete existing vim-table-mode and then try.

**Comment by gamStar** [comment]
Thanx again.

On the GitHub page for table-mode you recommend using NeoBundle or pathogen. Do you still recommend these? If I were to clean this all up and just use one bundle manager, which one would you recommend?

:: paul

**Comment by dhruvasagar** [comment]
Use whatever you like, Vundle, NeoBundle, pathogen, most are fine. I myself actually switched to using vim-plug sometime back so I don't use NeoBundle anymore.

**Comment by dhruvasagar** [comment]
I am hoping updating vim-table-mode fixed the issue, kindly reopen if you are still facing this issue.
