### ISSUE TITLE
Update formula on row delete/add

### ISSUE THREAD

**Issue by Miesco** [dhruvasagar/vim-table-mode#85]
How about a feature to add a new row to update the formulas?  Or even if you just manually add a row
and do `:call AddRow()`.  It means "add this row".  This will do the following:

Let `n` be current row, on `:call AddRow()`, check all expressions in the "tmf".
For each `$x,1` entry, if `x >= n`, then add one to `x`.

In the example below, you would add the row manually, and `:call AddRow()`.  Since the
current row is 3 (table 2), and it has "tmf: $3,1=...", it would change it to "tmf:
$4,1=...".

Table 1:

      | num1 | num2 |
      |------+------|
      | 3    | 4    |
      | 5    | 6    |
      | 8.0  | 1    |
      /* tmf: $3,1=Sum(1:-1) */

Would update to this:

Table 2:

      | num1 | num2 |
      |------+------|
      | 3    | 4    |
      | 5    | 6    |
      | 10   | 2    | <- new row, type `:call AddRow()`
      | 18.0 | 1    |
      /* tmf: $4,1=Sum(1:-1) */

All numbers in the format line representing rows (above or equal to the row added) would also have to be incremented by one.

**Comment by dhruvasagar** [comment]
Hi, I have already thought about these situations, vim-table-mode provides a way to deal with them, it is as simple as this : 
````
| num1 | num2 |
|------+------|
| 3    | 4    |
| 5    | 6    |
| 8.0 | 1    |
/* tmf: $-1,1=Sum(1:-1) */
```
As you can see, the difference is that the target cell is referenced by a negative index, which is a count from last. This way, if you were to add any number of rows, the formula will still work as you'd expect.
