### ISSUE TITLE
multiple formula for formula line

### ISSUE THREAD

**Issue by Ron89** [dhruvasagar/vim-table-mode#86]
Is there a way to insert multiple formula in formula line? For example if I need formula for multiple cells in the table? Currently if I add a formula with another formula already exist, old formula will simply be replaced, and yet the table will not be changed.

**Comment by dhruvasagar** [comment]
Hi,

How are you trying to add a formula ? Table Mode supports multiple formulas and the shortcut <kbd><Leader>tfa</kbd> enables you to add multiple formulas if you call it multiple times, you just have to call it from within the table on the target cell.

Alternatively you can also manually add multiple formulas delimited with a `;`.
Example : 

````
| num1 | num2 |
|------+------|
| 3    | 4    |
| 5    | 6    |
| 10   | 2    |
| 18.0 | 12.0 |
/* tmf: $-1,1=Sum(1:-1) ; $-1,2=Sum(1:-1) */
```

**Comment by Ron89** [comment]
I added formula as such:
with table
```
    | sfa   | meow |
    +=======|======+
    | 100   | 50   |
    | 23    | 59   |
    |       |      |
```
I use `TableFormulaAdd` function at cell 3,1, type
```
    Sum(1:-1)
```
formula correctly inserted as `#  tmf: $3,1=Sum(1:-1) `. Then I move to cell 3,2, invoke same function, same equation, the formula line is replaced with `#; $3,2=Sum(1:-1)` and no cell has changed its value.

**Comment by dhruvasagar** [comment]
Then that seems like a bug, what file type is this ? I will try reproduce it and let you know.

**Comment by dhruvasagar** [comment]
Also kindly share your vim-table-mode settings you have in your vimrc.

**Comment by Ron89** [comment]
It's in orgmode file, from [vim-orgmode](https://github.com/jceb/vim-orgmode). So the formula is actually filetype dependant?

**Comment by Ron89** [comment]
These are my settings
```
    if exists(":TableModeToggle")
        nnoremap <Leader>tm :TableModeToggle<CR>
        let g:table_mode_corner="|"
        let g:table_mode_corner_corner="+"
        let g:table_mode_header_fillchar="="
    endif
```

**Comment by dhruvasagar** [comment]
It is not, I just want to be able to reproduce the issue. I tried in regular text files and it works as expected.

**Comment by dhruvasagar** [comment]
What version of vim-table-mode are you using ?

**Comment by Ron89** [comment]
It's not `table-mode` related, I used it on my vim script, result is the same.
I am using vim-plugged to source your repo. I just updated it today.

**Comment by Ron89** [comment]
It appears as if plaintext is the only case that is working fine. markdown file also presents same issue.

**Comment by dhruvasagar** [comment]
Ok, I am able to reproduce the issue, looks like when the comment character is `#` there is an issue. Will look into it and let you know. In the meanwhile you can add multiple formulas manually and it should work as the example I provided.

**Comment by Ron89** [comment]
Noted, thanks for the prompt respond. Sorry my vim script is not fluent enough to provide much help...

**Comment by dhruvasagar** [comment]
No problem, thanks for reporting the issue.
