### ISSUE TITLE
when set paste vim-table-mode do not work

### ISSUE THREAD

**Issue by DouglasOY** [dhruvasagar/vim-table-mode#87]
when I add the line "set paste" in .vimrc in linux. the vim-table-mode do not work.

**Comment by dhruvasagar** [comment]
Will have a look.

**Comment by tukoz** [comment]
I can confirm @DouglasOY's catch: set paste breaks automation as well as `:Tableize`.

**Comment by dhruvasagar** [comment]
I am not sure if paste mode should be supported. I personally don't use paste mode as much so kindly elaborate on how it may be useful in the context of table mode ?

If you paste outside of paste mode, vim-table-mode works exactly like it should (assuming you enabled it).
