### ISSUE TITLE
error e54 in markdown files

### ISSUE THREAD

**Issue by Konfekt** [dhruvasagar/vim-table-mode#89]
After `<leader>tm` and typing in an empty markdown file
```markdown
| helpful | not |
```
there comes:
```vim
Error detected while processing function tablemode#TableizeInsertMode:
line    1:
E54: Unmatched \(
E54: Unmatched \(
line    4:
E54: Unmatched \(
E54: Unmatched \(
```

**Comment by dhruvasagar** [comment]
Thanks for reporting, will have a look soon.

**Comment by Konfekt** [comment]
Ok, it actually already happens right after typing the first |. This doesn't occur in a Text file though.

**Comment by Konfekt** [comment]
Hello, the cause is commentstring=[//]:\ #\ (%s)

**Comment by dhruvasagar** [comment]
OK thanks for that should be able to escape those characters for building
comment regex

**Comment by Konfekt** [comment]
Yeah, it's only about the ()  part.

**Comment by dhruvasagar** [comment]
Hey,

Are you using some special markdown plugin ? That `commentstring` looks rather weird and it's proving to be rather challenging to deal with.

**Comment by Konfekt** [comment]
See https://stackoverflow.com/questions/4823468/comments-in-markdown that recommends it as best practice. Perhaps I could help? If it's a regex, how about embracing `commentstring` by `\V`and `\m` to interpret it literally?

**Comment by Konfekt** [comment]
Also, note that only `()` needs to be escaped. Everything else does not cause trouble.

**Comment by dhruvasagar** [comment]
I am aware of that, the regex that I build is by splitting the `commentstring` by `%s` so that I can place the content between them in case it's commented. This problem is where we're trying to compare and match whether it's the starting of a table line (including comment starting expression optionally).

**Comment by dhruvasagar** [comment]
As per my tests, this should fix it, let me know if it's still a problem.

**Comment by Konfekt** [comment]
Thanks! It's fixed.
