### ISSUE TITLE
Allow multiple formula lines

### ISSUE THREAD

**Issue by expipiplus1** [dhruvasagar/vim-table-mode#90]
As far as I can tell, all the formulas for cells need to be squashed onto one line, which makes editing them difficult.

**Comment by dhruvasagar** [comment]
That's true, it should be allowed, i'll work on it, thanks for pointing it out.

**Comment by expipiplus1** [comment]
looking forward to it, thanks

**Comment by dhruvasagar** [comment]
Hi, took a while, but i've managed to find time to implement this. Now we can have multiple formula lines in the same format as previously defined but directly one after the other at the end of the table.

You should be able to evaluate the formulas as expected from within the table or while on any of the formula lines

**Comment by expipiplus1** [comment]
Thanks!
