### ISSUE TITLE
Formula for last row

### ISSUE THREAD

**Issue by Miesco** [dhruvasagar/vim-table-mode#95]
Could you please add a way to add a formula for the last row?

E.g.,

    | item  | num1 | num 2 |
    |-------|------|-------|
    | one   | 2    | 3     |
    | two   | 4    | 4     |
    | total |      |       |
    /* fmt: $,-1 = Sum(1:-1) */

Is there a features that conflict with this?

**Comment by dhruvasagar** [comment]
This is not possible at the moment, you can define for last row given a column, but not for the entire row. May not be very intuitive / much needed use case.
