### ISSUE TITLE
Extended ASCII Table

### ISSUE THREAD

**Issue by klassegeljakt** [dhruvasagar/vim-table-mode#96]
I have looked through the doc but didn't find a way to generate extended ascii tables like the one seen in the picture. I know possible to assign custom characters for corners, lines and separators. The problem is that extended ascii tables have 9 different types of corners as opposed to 1 which the cucumber tables have. Will these tables be supported at some point?

![](https://i.gyazo.com/dc0a10b02c2ac904c5e97954081bbdd6.png)

**Comment by dhruvasagar** [comment]
The tables generated with default settings is exactly like this, the only thing is you have to manually add the separators by using the `||` binding.
